CREATE TABLE AGENDAMENTOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PACIENTE_CPF VARCHAR2(20),
    MEDICO_NOME VARCHAR2(100),
    DATA VARCHAR2(10) NOT NULL,
    HORARIO VARCHAR2(5) NOT NULL
);

CREATE TABLE CONSULTAS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PACIENTE_NOME VARCHAR2(100) NOT NULL,
    PACIENTE_CPF VARCHAR2(20),
    MEDICO VARCHAR2(100),
    ESPECIALIDADE VARCHAR2(100),
    DATA VARCHAR2(10) NOT NULL,
    HORARIO VARCHAR2(5) NOT NULL,
    PROBLEMA VARCHAR2(200)
);

CREATE TABLE ENFERMEIROS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    COREN VARCHAR2(20) NOT NULL,
    SETOR VARCHAR2(100)
);

CREATE TABLE MEDICOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    CRM VARCHAR2(20) NOT NULL,
    ESPECIALIDADE VARCHAR2(100)
);

CREATE TABLE PACIENTES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CPF VARCHAR2(20) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    IDADE NUMBER,
    PROBLEMA VARCHAR2(200),
    PRONTUARIO VARCHAR2(200)
);

CREATE TABLE PRONTUARIOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PACIENTE_NOME VARCHAR2(100) NOT NULL,
    OBSERVACOES VARCHAR2(300),
    MEDICO_NOME VARCHAR2(100),
    CID VARCHAR2(20)
);

CREATE TABLE SETORES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ANDAR VARCHAR2(10),
    RESPONSAVEL VARCHAR2(100)
);